language: go

install:
  - wget https://raw.github.com/go-gl/testutils/master/travis-helper-functions.sh
  - source travis-helper-functions.sh

script:
  - go build -v

after_script:
  - go test -v
  - upload_to_imgur

after_failure:
  - echo
  - cat error.log
  - upload_to_imgur
after_error:
  - echo
  - cat error.log
  - upload_to_imgur

notifications:
  email:
    recipients:
      - peter@pwaller.net
      #- jimteeuwen@gmail.com
    #on_success: always
    on_failure: always