language: go

install:
  - date +%H:%M:%S.%N &>> error.log
  - sudo apt-get install eatmydata &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - yes | sudo apt-add-repository ppa:bumblebee/stable &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - sudo apt-get update -qq &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - sudo eatmydata apt-get install -qq libglfw-dev libglew-dev virtualgl mesa-utils inotify-tools &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - sudo vglserver_config -config +s +f &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - sudo mkdir -p /tmp/.X11-unix &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  # Start the X server, giving us enough time to get to inotifywait
  - (sleep 5 && sudo start lightdm) &>> error.log &
  - date +%H:%M:%S.%N &>> error.log
  # Wait for the X server to start
  - inotifywait /tmp/.X11-unix &>> error.log
  - export DISPLAY=:0
  - date +%H:%M:%S.%N &>> error.log
  - ((vglrun -d :0 -c proxy glxgears &) && sleep 1 && pkill glxgears) &>> error.log
  - date +%H:%M:%S.%N &>> error.log
  - go get -d -v
  # Fetch test dependencies
  - go list -f '{{range .TestImports}}{{.}} {{end}}' | go get -d -v

script:
  - go build -v

after_script:
  - go test -v
  - ls -la
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod +x imgurbash.sh
  - ./imgurbash.sh TestWindowCoords.png
  - ls -la

after_failure:
  - echo
  - cat error.log
after_error:
  - echo
  - cat error.log

notifications:
  email:
    recipients:
      - peter@pwaller.net
      #- jimteeuwen@gmail.com
    #on_success: always
    on_failure: always